Fix gd2/gd2_read.c:8:6: error: 'error' may be used uninitialized in this function [-Werror=maybe-uninitialized]
Also report about any error, not only the last one.

(cherry picked from commit 2b3dd57a6ccb2940f2e9119ae04e14362e2a1f61)