Initialize platform_specific variable in gdft.c
This addresses:
compile error C4703: potentially uninitialized local pointer variable 'platform_specific'

(cherry picked from commit f7ccdde67fb38ec12850d9b0e5aeb2a6f92284a2)