Fix deprecared function prototypes
Fixes following errors:
error: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]

Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit 7dae72496749f6d059e191e39fdfbf3de4025cac)